# Generated by Django 4.2.2 on 2023-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('abstract_description', models.TextField(blank=True)),
                ('image_id', models.CharField(max_length=256)),
                ('command_to_execute', models.CharField(max_length=1024)),
                ('exit_value_handler', models.CharField(choices=[('logging', 'logging')], max_length=64)),
                ('stderr_handler', models.CharField(choices=[('pythonTraceback', 'python traceback')], max_length=64)),
            ],
        ),
    ]
