# Generated by Django 4.2.2 on 2023-06-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
    ]
