# Generated by Django 4.2.2 on 2023-06-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_process_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('abstract_description', models.TextField(blank=True)),
                ('use_as', models.CharField(choices=[('commandLineArgument', 'command line argument')], max_length=64)),
                ('input_type', models.CharField(choices=[('bbox', 'bounding box'), ('double', 'double'), ('string', 'string')], max_length=64)),
                ('default_value', models.CharField(blank=True, max_length=256, null=True)),
                ('sort_order', models.IntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInputAllowedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('process_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.processinput')),
            ],
        ),
    ]
