# Generated by Django 4.2.2 on 2023-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_processinput_allowed_values_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['title'], 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='processinput',
            options={'ordering': ['process', 'sort_order']},
        ),
        migrations.AddField(
            model_name='processinput',
            name='crs',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
