# Generated by Django 4.2.2 on 2023-06-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_process_options_alter_processinput_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('abstract_description', models.TextField(blank=True)),
                ('read_from', models.CharField(choices=[('file', 'file')], max_length=64)),
                ('path', models.CharField(blank=True, max_length=1024, null=True)),
                ('output_type', models.CharField(choices=[('quakeml', 'quakeml')], max_length=64)),
                ('schema', models.CharField(blank=True, max_length=1024, null=True)),
                ('sort_order', models.IntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.process')),
            ],
            options={
                'ordering': ['process', 'sort_order'],
            },
        ),
    ]
