# Generated by Django 4.2.2 on 2023-06-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_processoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='working_dir',
            field=models.CharField(default='.', max_length=1024),
            preserve_default=False,
        ),
    ]
