# Generated by Django 4.2.2 on 2023-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_processinput_command_line_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinput',
            name='path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='stderr_handler',
            field=models.CharField(choices=[('pythonTraceback', 'python traceback'), ('logging', 'logging')], max_length=64),
        ),
        migrations.AlterField(
            model_name='processinput',
            name='input_type',
            field=models.CharField(choices=[('bbox', 'bounding box'), ('double', 'double'), ('string', 'string'), ('quakeml', 'quakeml'), ('xml', 'xml'), ('json', 'json')], max_length=64),
        ),
        migrations.AlterField(
            model_name='processinput',
            name='use_as',
            field=models.CharField(choices=[('commandLineArgument', 'command line argument'), ('file', 'file')], max_length=64),
        ),
        migrations.AlterField(
            model_name='processoutput',
            name='output_type',
            field=models.CharField(choices=[('quakeml', 'quakeml'), ('json', 'json'), ('shapefile', 'shapefile')], max_length=64),
        ),
    ]
